import type { VercelRequest, VercelResponse } from '@vercel/node';

// Long-form orchestrator: coordinates segmentation → audio → chunks → render
// This is the entry point for scripts longer than 15 seconds.
// It calls the Mac Mini render server at localhost:4100 for heavy processing.

const RENDER_SERVER = process.env.RENDER_SERVER_URL || 'http://localhost:4100';

export const config = { api: { bodyParser: { sizeLimit: '5mb' } } };

export default async function handler(req: VercelRequest, res: VercelResponse) {
  if (req.method !== 'POST') return res.status(405).json({ error: 'Method not allowed' });

  const { segments, script, path: vidPath, parameters, voiceId, packId } = req.body;

  if (!segments?.chunks?.length) return res.status(400).json({ error: 'segments with chunks required' });

  try {
    // Create a job ID
    const jobId = `lf-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;

    // Build the render job payload
    const renderJob = {
      id: jobId,
      audioUrl: '', // Will be generated by render server
      totalDurationSec: segments.totalDurationSec,
      chunks: segments.chunks,
      captions: [],
      captionStyle: {
        font: 'Arial', fontSize: 42, color: '#FFFFFF',
        activeColor: '#D4A843', inactiveColor: 'rgba(255,255,255,0.6)',
        outlineColor: '#000000', outlineWidth: 2,
        position: 'bottom-third', animation: 'word-by-word', maxWordsPerLine: 6,
      },
      musicVolume: -24,
      fps: 30,
      width: 1080,
      height: 1920,
      codec: 'h264',
      crf: 20,
      outputPath: `./output/${jobId}.mp4`,
      scriptFull: script,
      path: vidPath || 'ugc',
      createdAt: new Date().toISOString(),
      // Pass through for chunk generation
      parameters,
      voiceId,
      packId,
    };

    // Send to render server on Mac Mini
    const renderRes = await fetch(`${RENDER_SERVER}/render`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(renderJob),
    });

    if (!renderRes.ok) {
      const err = await renderRes.text();
      return res.status(500).json({ error: `Render server error: ${err}` });
    }

    const result = await renderRes.json();
    return res.json({ jobId, status: 'accepted', renderServer: RENDER_SERVER });
  } catch (err: any) {
    return res.status(500).json({ error: err.message });
  }
}
